name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.6'

      - name: Install Dependencies
        run: nimble install -y --depsOnly

      - name: Run Tests
        run: nimble test
